# Generated by Django 4.0.5 on 2024-12-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_remove_vehiculo_fecha_fabricacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede ver el catalogo')]},
        ),
    ]
